import { Component } from '@angular/core';

@Component({
  selector: 'app-grad2024',
  templateUrl: './grad2024.component.html',
  styleUrls: ['./grad2024.component.css']
})
export class Grad2024Component {
  majors = [
    'Accounting',
    'Advertising',
    'Aerospace',
    'African American Studies',
    'African Languages',
    'Agricultural Education and Communication',
    'Agricultural Operation Management',
    'Animal Sciences',
    'Anthropology',
    'Applied Physiology and Kinesiology',
    'Arabic',
    'Architecture',
    'Art History',
    'Art',
    'Astronomy and Astrophysics',
    'Biological Engineering',
    'Botany',
    'Business Administration',
    'Chemical Engineering',
    'Chemistry',
    'Chinese',
    'Civil Engineering',
    'Classical Studies',
    'Communication Sciences and Disorders',
    'Computer Engineering',
    'Computer Science',
    'Construction Management',
    'Criminology',
    'Dance',
    'Data Science',
    'Dietetics',
    'Digital Arts and Sciences',
    'Dual Languages',
    'Early Childhood Education',
    'Economics',
    'Education Sciences',
    'Electrical Engineering',
    'Elementary Education',
    'Engineering',
    'English',
    'Entomology and Nematology',
    'Environmental Engineering',
    'Environmental Management in Agriculture and Natural Resources',
    'Environmental Science',
    'Family Youth and Community Services',
    'Finance',
    'Fire and Emergency Services',
    'Food and Resource Economics',
    'Food Science',
    'Foreign Languages and Literatures',
    'Forest Resources and Conservation',
    'French and Francophone Studies',
    'Geography',
    'Geology',
    'Geomatics',
    'German',
    'Graphic Design',
    'Health Education and Behavior',
    'Health Science',
    'Hebrew',
    'Hispanic and Latin American Languages, Literatures, and Linguistics',
    'History',
    'Industrial and Systems Engineering',
    'Information Systems',
    'Interdisciplinary Studies',
    'Interior Design',
    'International Studies',
    'Italian',
    'Japanese',
    'Jewish Studies',
    'Journalism',
    'Landscape Architecture',
    'Linguistics',
    'Management',
    'Marine Sciences',
    'Marketing',
    'Materials Science and Engineering',
    'Mathematics',
    'Mechanical Engineering',
    'Media Production, Management, and Technology',
    'Meteorology',
    'Microbiology and Cell Science',
    'Music Education',
    'Music',
    'Natural Resource Conservation',
    'Nuclear Engineering',
    'Nursing',
    'Nutritional Sciences',
    'Pharmacy',
    'Philosophy',
    'Physics',
    'Plant Science',
    'Political Science',
    'Portuguese',
    'Psychology',
    'Public Health',
    'Public Relations',
    'Religion',
    'Russian',
    'Sociology',
    'Soil, Water, and Ecosystem Sciences',
    'Spanish',
    'Spanish and Portuguese',
    'Sport Management',
    'Statistics',
    'Sustainability and the Built Environment',
    'Sustainability Studies',
    'Theatre',
    'Theatre Performance',
    'Theatre Production',
    'Tourism, Hospitality, and Event Management',
    'Wildlife Ecology and Conservation',
    'Women\'s Studies',
    'Zoology'
  ];  
}
